greatscottgadgets/facedancer

facedancer/USBProxy.py

Minor change to how we select USB devices to be proxied.  Pass through keyword args, find all devices, and use index to select specific device.

USBProxy: allow multiple identical targets to be proxied

---

facedancer/USBConfiguration.py

If an emulated device has alternate settings, don't count them as unique interfaces to avoid the wrong number appearing in the returned descriptor.
Problematic example:
```
class USBDemoDevice(USBDevice):
name = "USB demo device"
def __init__(self, maxusb_app, verbose=0):
interfaces = [
USBDemoInterface(verbose=verbose, number=0, alternate=0),
USBDemoInterface(verbose=verbose, number=0, alternate=1),
USBDemoInterface(verbose=verbose, number=0, alternate=2),
USBDemoInterface(verbose=verbose, number=0, alternate=3)
]
config = USBConfiguration(
1,                  # index
"Demo config",      # string desc
interfaces          # interfaces
)
```
Outcome:
`[ 2673.631360] usb 1-3: config 1 has 1 interface, different from the descriptor's value: 4`

USBConfiguration: Only count proper interfaces, not alternate settings.

---

USBKeyboard.py

modifiers (e.g. holding shift while sending key) should be the first byte in the HID response

fix HID modifiers

---

USBKeyboard.py
facedancer-keyboard-interactive.py

Supports entering printable characters with Ctrl and Shift modifiers and
a few special keys like Enter, Delete, Backspace, etc.
Requires python curses.
Tested with FaceDancer21.
Originally written for the old goodfet-based FaceDancer: https://github.com/xairy/facedancer-utils

facedancer: add interactive keyboard

---

facedancer/USBConfiguration.py
facedancer/USBDevice.py
facedancer/USBEndpoint.py
facedancer/USBInterface.py

Using "struct.unpack_from" instead of "struct.unpack" so that it works for descriptors longer than spec defined sizes.

Support descriptors with non-standard length.

---

facedancer/USBDevice.py

Previously, a class request with endpoint as the recipient and with `wIndex != 1` would fail, as USBEndpoint doesn't have a `device_class` attribute.

Have the device interface handle class requests to endpoint

---

legacy-applets/facedancer-keyboard-interactive.py

By always responding to requests, otherwise the endpoint stops being polled.
(Requires the revert from #36 to work properly.)

facedancer: make interactive keyboard work with GreatFET One

---

facedancer/USBDevice.py
facedancer/future/device.py

If USBDevice.max_packet_size_ep0 was set to a value
smaller than 64 the pakets send to the host were
still 64 bytes in size.

Support max packet size < 64 of endpoint 0 correctly

---

pyproject.toml

This PR contains:
1. Metadata updates for authors 
2. A shim for `setup.py` as CI still relies on a `python setup.py` flow

Packaging: migrate from setup.py to pyproject.toml

---

facedancer/future/device.py

As of Python 3.11 support for generator-based coroutines are deprecated and have been removed.
As a consequence the use of `Iterable[asyncio.coroutine]` in a type annotation causes the python interpreter to fail.
This commit updates type annotations to use `Iterable[Coroutine]` instead.
More information: [Generator-based Coroutines](https://docs.python.org/3.10/library/asyncio-task.html#generator-based-coroutines)

future: bring type annotations up to date with Python >= 3.11

---

examples/template.py

Hello neighbors,
I've just started digging a bit deeper into FaceDancer and I have a really really tiny contribution to the device template for you.
I've noticed that the ```USBDirection``` is set to ```IN``` twice, that is for the ```TemplateOutEndpoint``` class as well.
I guess this is a typo, right?
Cheers 😊

Mistyped endpoint direction in the device template

---

facedancer/devices/umass/umass.py

Rebase of: #68 
> The current code only supports 32-bit LBAs and does not support 64-bit LBAs.
> Therefore, when a disk of 2 TiB or larger is connected, "READ CAPACITY" does not report the correct capacity. (However, if the disk is initialized with GPT, the current code can still be used.)
> To improve this, "READ CAPACITY (16)", "READ (16)", and "WRITE (16)" have been implemented.
> 
> ![214334351-07389d4d-6c99-4b29-9ce8-1afe759bf504](https://github.com/greatscottgadgets/facedancer/assets/44808/0d71093a-0621-4fc0-b621-c1c9fb9fb3ac)
>

 64bit LBA support (> 2TiB disk support)

---

examples/template.py

Endpoint 0 is reserved by the spec as the default pipeline. Attempting to emulate a device with an endpoint numbered 0 causes an issue where there is no packet flow after the host is correctly configured. This can be quite painful to debug & is probably a common mistake, since interface numbers are annotated in this template as 'should have a unique index, starting from 0'.

Add note about endpoint numbers to template.py

---

facedancer/proxy.py

I just received my Cynthion yesterday - thank you, it's awesome!
However, I'm having a little problem: Upon shutdown, when the libusb context is getting destroyed, I get the error LIBUSB_ERROR_BUSY (using usbproxy):
```
Traceback (most recent call last):
File "/mnt/source/facedancer/venv/lib/python3.12/site-packages/facedancer/proxy.py", line 356, in _destroy_libusb_context
cls.device_handle.attachKernelDriver(number)
File "/mnt/source/facedancer/venv/lib/python3.12/site-packages/usb1/__init__.py", line 1207, in attachKernelDriver
mayRaiseUSBError(
File "/mnt/source/facedancer/venv/lib/python3.12/site-packages/usb1/__init__.py", line 127, in mayRaiseUSBError
__raiseUSBError(value)
File "/mnt/source/facedancer/venv/lib/python3.12/site-packages/usb1/__init__.py", line 119, in raiseUSBError …
```

LIBUSB_ERROR_BUSY upon shutdown

---

examples/template.py
facedancer/device.py

This will break bcdUSB (`usb_spec_version`) and bcdDevice (`device_revision`) usage in existing scripts that specify them, but I think it is correct to do so as it fixes a bug. The spec is clear about the byte order of these fields and explicitly says "version 2.0 is represented with a value of 0x0200".

Correct byte order of bcdUSB and bcdDevice

---

README.md
facedancer/backends/__init__.py
facedancer/backends/hydradancer.py

Here are some characteristics and results of this backend, which I think would make it a good addition to this project:
* supports USB2 High-speed, Full-speed and should support low-speed
* 6 endpoints including EP0, in both IN/OUT directions simultaneously
* endpoint numbers from 0 to 7
* increased speed compared to Facedancer21/GreatFET One, results here https://github.com/HydraDancer/hydradancer_fw
* support for NAKs, but also priming using `handle_buffer_empty`
* tested emulation of a mouse peripheral and the included mass storage example
* tested proxy mode with a High-speed USB key (got 1.5MB transfer rate while proxying a 1.5GB file), tested proxy mode with a Full-speed mouse

New Hydradancer backend for Facedancer

---

examples/coroutine.py
examples/minimal.py
facedancer/device.py
facedancer/devices/__init__.py
facedancer/errors.py

This PR attempts to resolve the tension between:
- Being able to exit an emulation in order for a) the `--suggest` argument to work and b) just having something nicer than crashing out of the emulation with a `SIGINT` versus…
- Not interfering with any external scripts running one or more emulations.
~~I propose that we dedicate an unused key-combination (at the time of writing this is `Control-E`) that can be polled for in an `exit_handler()` co-routine.~~
The final approach taken is to catch the `KeyboardInterrupt` exception in the `default_main()` helper function allowing users to gracefully exit from the emulation by pressing `Control-C`.
For users who may require different behavior a new example has been added: `examples/coroutine.py` which demonstrates how to write a custom …

Allow Control-C to gracefully exit a Facedancer emulation

---

facedancer/device.py

When running with `--suggest`, Facedancer will output request handler suggestions.
Where these requests apply to an interface or endpoint, these handlers are decorated with `@to_this_interface` or `@to_this_endpoint`, but there is nothing to say _which_ interface or endpoint these handlers should be attached to.
This PR fixes that by grouping the suggestions according to where they should be placed.
Example output:
```
Request handler code:
On interface 0:
@class_request_handler(number=131, direction=USBDirection.IN)
@to_this_interface
def handle_control_request_131(self, request):
request.stall()
@class_request_handler(number=1, direction=USBDirection.OUT)
@to_this_interface
def handle_control_request_1(self, request):
request.stall()
@class_request_handler(number=129, …
```

Group request handler suggestions by the recipients they belong to

---

facedancer/device.py
facedancer/endpoint.py
facedancer/interface.py

Nested type annotations are only supported from 3.9 onwards.
e.g. 
```
attached_descriptors : List[USBDescriptor] = field(default_factory=list)
```

repo: support nested type annotations on Python < 3.9

---

facedancer/backends/moondancer.py

If there's a Cynthion device available but libgreat couldn't claim access to it, it throws an IOError. This catches that and logs a message for the user.

moondancer: log a warning for permissions errors

---

CHANGELOG.md
facedancer/classes/hid/descriptor.py
facedancer/descriptor.py
facedancer/devices/keyboard.py

This PR does a bunch of things:
* There is some ancient confusion in bits of the codebase when referring to a descriptor's `number` and `type_number`. The `number` is the descriptor _number_ whereas `type_number` is the descriptor _type_. This was causing identifier lookups to fail when searching for a descriptor in `requestable_descriptors`.
* The `Keyboard` device's `HIDDescriptor` also needed to specify `include_in_config`.
* The data class for `USBClassDescriptor` needed a type annotation.
---
closes #133

Get rubber-ducky example working with new descriptor features.

---

facedancer/backends/MAXUSBApp.py
facedancer/backends/base.py
facedancer/backends/greatdancer.py
facedancer/backends/hydradancer.py
facedancer/backends/moondancer.py

PR #122 added support for alternate interface settings, but currently, backends only set up endpoints on a call to `configured()`, and have no API to support changing which endpoints are in use on a `SET_INTERFACE` request.
However, it turns out that things mostly work anyway, because current backends will simply iterate over all interface definitions when looking for endpoints to set up, and thereby set up the union of all endpoint addresses used by any interface definitions in the configuration.
This is actually a viable approach, _provided_ that none of these endpoint addresses are used in different ways by multiple interface definitions. Therefore, rather than trying to implement on-the-fly remapping of available endpoints in each backend, for now we can simply reject configurations …

Reject unsupported configurations in backends

---

facedancer/__init__.py
facedancer/classes/hid/descriptor.py
facedancer/configuration.py
facedancer/descriptor.py
facedancer/device.py
facedancer/endpoint.py
facedancer/interface.py
facedancer/magic.py

This PR collects followup changes that build on the descriptor API work from #126.
Key changes are:
- Descriptors attached to endpoints are now instantiated (replaces #139)
- The `instantiate_subordinates` function is redesigned to avoid silent dropping of subordinates with duplicate identifiers (replaces #140).
- Orderings of declaration/insertion of subordinates are preserved, allowing control of ordering in binary configurations.
- Fixes to convert some fields to the right types in `from_binary_descriptor` methods.
- A dictionary of known strings and their indexes may be passed to `from_binary_descriptor` methods.
- The `number` field of `USBDescriptor` is made optional, as it is not required for descriptors attached in a configuration.
- The `type_number` field will now be inferred …

Descriptor API tweaks

---

facedancer/descriptor.py

`itertools.batched` only shows up from Python `>=3.12` -- this PR adds a smol shim to tide us over.

repo: use a shim instead of itertools.batched

---

pyproject.toml

This PR:
* Drops support for Python 3.8 as it has reached end of life. 
* Drops support for Python 3.9 as it does not support the `kw_only` parameter for `dataclass`.
For more information see: #145 #149
---
Closes #145

Update Python versions: drop 3.8, 3.9
